services:
  mongodb:
    image: 'mongo:latest'
    container_name: colis-mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=colis_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: colis-app
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=colis_db
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=secret
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin

  mongo-express:
    image: mongo-express:latest
    container_name: colis-mongo-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://root:secret@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false

volumes:
  mongodb_data:
